added func renderHTML and added form reg
ArtemGuschin8876/GameMasterWeb pull request #4
Opened 2024-06-16 00:38 UTC by ArtemGuschin8876

2024-06-16 16:42 UTC, monshq requested changes

2024-06-16 16:42 UTC, monshq commented on internal/data/users.go
> +	errTextRu = "Это поле является обязательным"
В имени переменной стоит указать, что это ошибка именно на обязательность

2024-06-16 16:42 UTC, monshq commented on static/ui/html/tableAllUsers.html
> +                <!-- @caller lib/ddproject_web/live/user_live/index.html.heex:21 (ddproject) --><!-- <Phoenix.Component.link> lib/phoenix_component.ex:2687 (phoenix_live_view) --><a href="/users/add"
Обычно принято делать страницу для создания `GET /users/new`, а сам запрос на создание `POST /users`

2024-06-16 16:42 UTC, monshq commented on cmd/api/addUsersHandler.go
>  	if c.Request().Method == http.MethodGet {
Так делать не надо, один хэндлер должен быть для одного метода

2024-06-16 16:42 UTC, monshq commented on cmd/api/addUsersHandler.go
> +	var user data.Users
Здесь рендерится промежуточная страница после успешного создания пользователя. Лучше просто редиректить на список пользователей

2024-06-16 16:42 UTC, monshq commented on static/ui/html/addUser.html
>                  <label for="af-submit-app-upload-images" class="inline-block text-sm font-medium text-gray-800 mt-2.5 dark:text-neutral-200">
Если поле не работает, то стоит его хотя бы закомментировать

2024-06-16 16:42 UTC, monshq commented on static/ui/html/addUser.html
> +                <input type="text" name="nickname" id="nickname" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" value="{{.User
Как минимум у полей ввода потерялись классы, поэтому они выглядят тонко и некрасиво. Стоит перепроверить, какой код был перенесён из оригинальных шаблонов.

2024-06-16 17:09 UTC, ArtemGuschin8876 commented on cmd/api/addUsersHandler.go
>  	if c.Request().Method == http.MethodGet {
Здесь не совсем понимаю что не так) и что сделать надо))

2024-06-16 18:04 UTC, monshq commented on cmd/api/addUsersHandler.go
>  	if c.Request().Method == http.MethodGet {
Этот метод должен обрабатывать только GET или только POST. Если у тебя на одном пути два разных действия - то разноси по разным хэндлерам

2024-06-17 12:43 UTC, ArtemGuschin8876 commented on cmd/api/addUsersHandler.go
>  	if c.Request().Method == http.MethodGet {
Сделал, и там еще был квест с редиректом, я тоже сделал и запушил

2024-06-17 13:52 UTC, monshq commented on cmd/api/addUsersHandler.go
> +	return c.Redirect(http.StatusSeeOther, "/users/successfully")
Ещё раз, смысл редиректа в том, чтобы не делать промежуточную страницу. Мы можем показать сообщение вверху страницы, что пользователя успешно создали, но это всё равно будет старая страница users. Такие сообщение мы будем делать позже.

2024-06-17 13:52 UTC, monshq commented on cmd/api/routes.go
> +	e.GET("/users/successfully", app.successfullCreatedUserHandler)
Этот роут должен убраться, продолжая мысль из комментария в хэндлере. Но на будущее: слова successfull нет, есть successful и successfully.

2024-06-17 13:52 UTC, monshq commented on internal/data/users.go
> +	bindingErrRuLang = "Это поле является обязательным"
bindingErr это не про обязательность

2024-06-17 13:52 UTC, monshq commented on static/ui/html/addUser.html
> +                <input type="text" name="name" id="name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" value="{{if .User.Name
Проверил локально, поле не заполняется автоматически, если в каком-то из полей на странице до этого была ошибка.

2024-06-17 14:56 UTC, ArtemGuschin8876 commented on cmd/api/addUsersHandler.go
> +	return c.Redirect(http.StatusSeeOther, "/users/successfully")
Понял, я просто отправлю на /users и выдам сообщение о том что пользователь создан)

2024-06-17 14:58 UTC, ArtemGuschin8876 commented on static/ui/html/addUser.html
> +                <input type="text" name="nickname" id="nickname" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" value="{{.User
Я потыкал из шаблонов который ты мне скинул, переделал классы, но это прям обязательно что бы они сейчас выглядели как-то по другому?)

2024-06-17 15:00 UTC, ArtemGuschin8876 commented on static/ui/html/addUser.html
> +                <input type="text" name="name" id="name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" value="{{if .User.Name
Здесь не понимаю, что должно заполняться автоматически?)

2024-06-17 16:07 UTC, ArtemGuschin8876 commented on cmd/api/addUsersHandler.go
> +	return c.Redirect(http.StatusSeeOther, "/users/successfully")
Было душно) но вроде сделал)

2024-06-17 16:08 UTC, ArtemGuschin8876 commented on internal/data/users.go
> +	bindingErrRuLang = "Это поле является обязательным"
Исправил

2024-06-18 19:58 UTC, monshq commented on cmd/api/routes.go
> +		e.Logger.Fatal("SECRET_KEY environment variable is required")
Вот тут явно вредительство :) В ошибке одно имя переменной, а ожидается другое

2024-06-18 19:58 UTC, monshq commented on static/ui/html/addUser.html
> +                <input type="text" name="nickname" id="nickname" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" value="{{.User
У тебя нет ссылки на tailwind на странице добавления пользователя. Его нужно добавлять так же, как это делали в таблице

2024-06-18 20:04 UTC, monshq commented on internal/data/users.go
> +	bindingErrRuLang = "Это поле является обязательным"
Где?

2024-06-18 20:04 UTC, monshq commented on cmd/api/addUsersHandler.go
> +		return jsendError(c, "session creation error")
Такие подробности пользователю можно не отдавать, для него это будет internal error. Главное залогировать.

И в целом подобные ошибки можно ловить в middleware через обработчик паник, как было в книге. Тогда не нужно будет проверять в каждом таком месте, отдавать json или html.

2024-06-18 20:04 UTC, monshq commented on cmd/api/addUsersHandler.go
> +	return c.Redirect(http.StatusSeeOther, "/users/successfully")
Да, flash сообщения - это то, как обычно такое делается. Молодец, что нашёл.

2024-06-18 20:05 UTC, monshq commented on cmd/api/main.go
> +		"./static/ui/html/successfullCreatedUser.html",
Этот файл уже не нужен?

2024-06-21 11:48 UTC, ArtemGuschin8876 commented on static/ui/html/addUser.html
> +                <input type="text" name="nickname" id="nickname" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" value="{{.User
Я добавил ссылку в addUser, теперь просто поля стали чёрными)) по мне до этого было лучше, но это дело вкуса)

2024-06-21 11:50 UTC, ArtemGuschin8876 commented on cmd/api/addUsersHandler.go
> +	return c.Redirect(http.StatusSeeOther, "/users/successfully")
Окей, я теперь не совсем понимаю когда резолвить коммент)

2024-06-21 11:50 UTC, ArtemGuschin8876 commented on internal/data/users.go
> +	bindingErrRuLang = "Это поле является обязательным"
mandatoryFieldRuLang вот же новое название)

2024-06-21 11:51 UTC, ArtemGuschin8876 commented on cmd/api/routes.go
> +		e.Logger.Fatal("SECRET_KEY environment variable is required")
Сори, не заметил)

2024-06-21 11:53 UTC, ArtemGuschin8876 commented on cmd/api/main.go
> +		"./static/ui/html/successfullCreatedUser.html",
Точно, спасибо, я уберу из кэша

2024-06-21 13:27 UTC, monshq commented on internal/data/users.go
> +	bindingErrRuLang = "Это поле является обязательным"
Похоже я не умею гитхабом пользоваться, да, всё ок

2024-06-21 13:29 UTC, monshq commented on static/ui/html/addUser.html
> +                <input type="text" name="name" id="name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" value="{{if .User.Name
Когда ты заполняешь поля, нажимаешь отправить, а тебе система выдаёт ошибку. Я жду, что при этом на следующей странице останутся введёнными поля, которые я уже заполнил.

2024-06-21 13:37 UTC, ArtemGuschin8876 commented on cmd/api/addUsersHandler.go
> +		return jsendError(c, "session creation error")
Сделал по книге, немного изменив)

2024-06-21 13:59 UTC, ArtemGuschin8876 commented on static/ui/html/addUser.html
> +                <input type="text" name="name" id="name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" value="{{if .User.Name
Сделал )

2024-06-21 14:36 UTC, monshq commented on cmd/api/routes.go
> +	e.GET("/users/edit/:id", app.editUserFormHandler)
Давай определимся с именами в crud методах. Обычно они звучат так:
```
GET /users - list
GET /users/:id - show
GET /users/new - new
POST /users - create
GET /users/:id/edit - edit
PUT /users/:id - update
DELETE /users/:id - delete
```

Соответственно методы должны этому соответствовать, например `showOneUserHandler` должен стать `showUserHandler`, а `editUserFormHandler` - `editUserHandler`.

Второе, у тебя накопилось достаточно функций с `Handler` в конце. Пришло время их выделить в отдельный модуль внутри `cmd/api`, назвать его, например, `handlers`, и избавиться от `Handler` в имени функций и файлов.

2024-06-21 14:36 UTC, monshq commented on cmd/api/updateUsersHandler.go
> +	}
У тебя не стандартная библиотека, у тебя echo. Если метод неправильный, то до обработчика дело не дойдёт, соответственно эта проверка лишняя.

2024-06-21 14:36 UTC, monshq commented on cmd/api/middleware.go
> +				c.JSON(http.StatusInternalServerError, errResponse)
Обычно в json api мы всегда отдаём статус 200, даже если что-то не так. Это позволяет нам отличать ошибки логики от ошибок инфраструктуры

2024-06-21 14:36 UTC, monshq commented on cmd/api/updateUsersHandler.go
> +		U:          user,
Не стоит называть переменные одной буквой, если они используются далеко от места, где определяются.

2024-06-21 14:37 UTC, monshq commented on cmd/api/addUsersHandler.go
> +		return jsendError(c, "session creation error")
Если мы теперь ловим паники, то здесь лучше паниковать, а не отдавать json ошибку.

2024-06-21 14:39 UTC, monshq commented on static/ui/html/addUser.html
> +                <input type="text" name="nickname" id="nickname" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" value="{{.User
Ладно, мы с тобой решили, что я тебе отправлю ПР с тем, чтобы выглядело получше. Подробно изучать html будет долго и нам вероятно не сильно нужно.

2024-06-21 14:44 UTC, monshq commented
Есть ещё надоедливый момент: когда мы заходим на localhost:4000, нам отдаёт 404. По идее нас должно кидать на лэндинг, но раз его нет, то давай сделаем редирект на `/users`.

2024-06-21 19:04 UTC, ArtemGuschin8876 commented on cmd/api/updateUsersHandler.go
> +		U:          user,
Исправил

2024-06-21 19:04 UTC, ArtemGuschin8876 commented on cmd/api/middleware.go
> +				c.JSON(http.StatusInternalServerError, errResponse)
Исправил

2024-06-21 19:04 UTC, ArtemGuschin8876 commented on cmd/api/updateUsersHandler.go
> +	}
Убрал

2024-06-21 19:07 UTC, ArtemGuschin8876 commented on cmd/api/routes.go
> +	e.GET("/users/edit/:id", app.editUserFormHandler)
А вот тут веселуха конечно, я переписал код т.к перенёс файлы в другой пакет, не знаю насколько это изящно :) Но вот с переименованием вообще интересная история, переименовываю файлы и начинается аншлаг, все ломается ( я то думал просто полетят импорты и нейминг) а там ошибки всех сортов, и можно увидеть что в папке handlers есть имена с Handlers и есть AddUser, я до сих пор не понимаю почему он переименовался хотя до этого красил мне проект в красный))

2024-06-22 09:10 UTC, monshq commented on cmd/api/updateUsersHandler.go
> +		U:          user,
Pointer лишнее, лучше просто User. И посмотри в шаблон, там тоже нужно имя переменной поменять

2024-06-22 09:13 UTC, monshq commented on cmd/api/routes.go
> +	e.GET("/users/edit/:id", app.editUserFormHandler)
https://echo.labstack.com/docs/context

Вот так можно определить свой контекст. В него можно записать app, и в handler'ах его доставать.

Ошибки всех сортов не увидел, кроме того, что отвалилась edit страница. Но это из-за переименования переменной из другого комментария

2024-06-23 15:44 UTC, ArtemGuschin8876 commented on cmd/api/updateUsersHandler.go
> +		U:          user,
Там просто в структуре есть как пользователь и он используется, так и поинтер на пользователя

2024-06-23 15:46 UTC, ArtemGuschin8876 commented on cmd/api/updateUsersHandler.go
> +		U:          user,
Вообщем жду некст тз, или фиксы))

2024-06-23 16:03 UTC, monshq commented on cmd/api/api_handlers/addUser.go
> +	cc := c.(*application.CustomContext)
А нельзя сразу параметром получать CustomContext?

2024-06-23 16:03 UTC, monshq commented on cmd/api/api_handlers/showListUsers.go
> +func ShowListUsers(c echo.Context) error {
Есть show, есть list, а тут франкенштейнов монстр.

2024-06-23 16:03 UTC, monshq commented on cmd/api/routes.go
> +	e.POST("/users", api_handlers.AddUsersHandler)
CreateUser

2024-06-23 16:03 UTC, monshq commented on internal/application/customContext.go
> +type CustomContext struct {
CustomContext звучит плохо. Можно сделать AppContext, например

2024-06-23 16:03 UTC, monshq commented on cmd/api/api_handlers/addUser.go
> +	User        data.Users
Структура для одного пользователя не должна называться во множественном числе, должно быть data.User

2024-06-23 16:03 UTC, monshq commented on cmd/api/api_handlers/addUser.go
> +	UserPointer *data.Users
Зачем нам и User, и UserPointer?

2024-06-23 16:03 UTC, monshq commented on cmd/api/routes.go
> +		e.Logger.Fatal("SECRET_KEY_FOR_SESSION environment variable is required")
SECRET_KEY_FOR_SESSION не сильно понятнее, чем SECRET_KEY, но длиннее и неудобнее, я бы выбрал второй вариант

2024-06-23 16:03 UTC, monshq commented on internal/application/app.go
> +	DB   struct {
В том го коде, что я видел, все struct'ы, которые используются в других struct'ах, были вынесены отдельно. Кажется, что здесь тоже лучше вынести вложенную структуру наверх. Или не переусложнять и сделать структуру плоской, ради одного значения делать вложенность смысла сильно нет.

2024-06-23 16:03 UTC, monshq commented on internal/data/templates.go
> +	Users      []Users
Это Users где-то используется?

2024-06-23 17:01 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/addUser.go
> +	cc := c.(*application.CustomContext)
Не совсем понимаю, сделалпо доке

2024-06-23 17:03 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/showListUsers.go
> +func ShowListUsers(c echo.Context) error {
Здесь тоже не понял в чем конкретно я не прав)

2024-06-23 17:05 UTC, ArtemGuschin8876 commented on cmd/api/routes.go
> +	e.POST("/users", api_handlers.AddUsersHandler)
Изменил

2024-06-23 17:06 UTC, ArtemGuschin8876 commented on internal/application/customContext.go
> +type CustomContext struct {
Сделал

2024-06-23 17:06 UTC, monshq commented on cmd/api/api_handlers/addUser.go
> +	cc := c.(*application.CustomContext)
Да, но попробуй принимать контекст сразу параметром. По идее это наследуемый тип, поэтому может работать. В таком случае не надо будет везде делать каст к нашему типу

2024-06-23 17:07 UTC, monshq commented on cmd/api/api_handlers/showListUsers.go
> +func ShowListUsers(c echo.Context) error {
Нужно просто ListUsers

2024-06-23 18:59 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/addUser.go
> +	User        data.Users
Сделал

2024-06-23 20:10 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/addUser.go
> +	UserPointer *data.Users
Исправил и очень долго ебался с тем что мне nil выходит итд) оказывается ты же мне днём поменял путь в роуте ебать я орал тут))) в хорошем смысле) но я переделал)

2024-06-23 20:12 UTC, ArtemGuschin8876 commented on cmd/api/routes.go
> +		e.Logger.Fatal("SECRET_KEY_FOR_SESSION environment variable is required")
ес

2024-06-24 14:49 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/showListUsers.go
> +func ShowListUsers(c echo.Context) error {
Сделал, и сделал квесты из тг, на exist полей и валидацию city

2024-06-24 14:58 UTC, ArtemGuschin8876 commented on internal/data/templates.go
> +	Users      []Users
Да при показе списка пользователей

2024-06-25 11:35 UTC, monshq commented on internal/application/customContext.go
> +type AppContext struct {
Файл тогда тоже переименовать надо

2024-06-25 11:35 UTC, monshq commented on migrations/000001_users.up.sql
> +ADD CONSTRAINT unique_nickname UNIQUE (nickname);
Обычно такое делается через [индекс](https://www.postgresql.org/docs/current/sql-createindex.html), например
```
CREATE UNIQUE INDEX ON users (email);
```

2024-06-25 11:35 UTC, monshq commented on cmd/api/api_handlers/createUser.go
> +type TemplateData struct {
Это зачем-то нужно? Или оно повторяет функционал из data/templates?

2024-06-25 11:43 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/addUser.go
> +	cc := c.(*application.CustomContext)
Здесь всё еще не понятно, ведь если дать параметром, то роуты ждут (echo.MiddlewareFunc) и я не совсем понимаю как это сделать))

2024-06-25 13:18 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/createUser.go
> +type TemplateData struct {
Сори, не заметил)

2024-06-25 13:18 UTC, ArtemGuschin8876 commented on migrations/000001_users.up.sql
> +ADD CONSTRAINT unique_nickname UNIQUE (nickname);
сделал

2024-06-25 13:18 UTC, ArtemGuschin8876 commented on internal/application/customContext.go
> +type AppContext struct {
сделал

2024-06-25 13:18 UTC, ArtemGuschin8876 commented on internal/application/app.go
> +	DB   struct {
готово

2024-06-25 13:35 UTC, monshq commented on cmd/api/api_handlers/addUser.go
> +	cc := c.(*application.CustomContext)
Попробовал у себя, напрямую не получается. Но можно сделать обёртку вокруг handler функций:

```golang
// Wrapper function to convert echo.Context to AppContext
func withAppContext(handler func(AppContext) error) func(echo.Context) error {
    return func(c echo.Context) error {
        appCtx := AppContext{Context: c}
        return handler(appCtx)
    }
}
...
e.POST("/users", withAppContext(api_handlers.CreateUser))
```

2024-06-25 13:35 UTC, monshq commented on internal/application/customContext.go
> +type AppContext struct {
не вижу

2024-06-25 13:37 UTC, monshq commented on migrations/000001_users.up.sql
> +CREATE UNIQUE INDEX ON users (nickname);
Только сейчас заметил, что ты уже смёрженную миграцию правишь. Так нехорошо. Эту миграцию другие пользователи у себя уже прогнали и ты их запутаешь. Нужно создать новую.

2024-06-25 13:38 UTC, monshq commented on cmd/api/api_handlers/createUser.go
> +// type TemplateData struct {
Раз оно больше не нужно, то стоит удалить

2024-06-25 15:18 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/createUser.go
> +// type TemplateData struct {
реди

2024-06-25 15:18 UTC, ArtemGuschin8876 commented on migrations/000001_users.up.sql
> +CREATE UNIQUE INDEX ON users (nickname);
реди

2024-06-25 15:18 UTC, ArtemGuschin8876 commented on internal/application/customContext.go
> +type AppContext struct {
реди

2024-06-25 15:35 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/addUser.go
> +	cc := c.(*application.CustomContext)
Запушил, но не понимаю в чем разница, так мне теперь в хендлере надо создавать 	app := a.App
	c := a.Context

2024-06-25 16:43 UTC, monshq commented on migrations/000001_users.up.sql
> +CREATE UNIQUE INDEX ON users (nickname);
не вижу

2024-06-25 16:58 UTC, monshq commented on cmd/api/api_handlers/createUser.go
> +	if err := c.Bind(&user); err != nil {
Ты этот же метод можешь вызвать на AppContext напрямую. Делать `c := a.Context` необязательно. Т.е.:

```golang
func CreateUser(c application.AppContext) error {
	var user data.User

	app := c.App

	if err := c.Bind(&user); err != nil {
		log.Println(err)
		return c.JSON(http.StatusOK, app.JsendError(c, "invalid request payload"))
	}
```

2024-06-25 16:59 UTC, monshq commented on cmd/api/routes.go
> +		appCtx := application.AppContext{Context: c}
Я немного неправильно здесь подсказал, так у тебя App в AppContext получается незаполненным. Плюс у нас уже контекст нужного типа, его осталось только конвертировать:
```golang
		appCtx := c.(*application.AppContext)
		return handler(*appCtx)
```

2024-06-28 16:19 UTC, ArtemGuschin8876 commented on cmd/api/api_handlers/createUser.go
> +	if err := c.Bind(&user); err != nil {
реди

2024-06-28 16:19 UTC, ArtemGuschin8876 commented on cmd/api/routes.go
> +		appCtx := application.AppContext{Context: c}
реди

2024-07-01 15:24 UTC, ArtemGuschin8876 commented on migrations/000001_users.up.sql
> +CREATE UNIQUE INDEX ON users (nickname);
реди

2024-07-01 15:37 UTC, monshq commented on migrations/000001_users.up.sql
> +CREATE UNIQUE INDEX ON users (nickname);
Оригинальные файлы с миграциями должны остаться неизменными

2024-07-01 16:07 UTC, ArtemGuschin8876 commented on migrations/000001_users.up.sql
> +CREATE UNIQUE INDEX ON users (nickname);
реди

2024-07-01 16:44 UTC, merged